### ISSUE TITLE
streaming server gets terminated not capable to handle CTRL+C

### ISSUE THREAD

**Issue by dvrogozh** [projectceladon/libvhal-client#7]
See: https://github.com/projectceladon/cloud-streaming

To reproduce:
1. Connecting AIC to encoding and streaming servers defined at https://github.com/projectceladon/cloud-streaming
2. Do not connect any client
3. Press CTRL+C in streaming container

Expectation is that streaming container will catch SIGINT sent by CTRL+C and normally terminate. Instead it gets aborted:
```
[7375] 1673386677.329581  [INFO] :  irrv-receiver: IRRV_CTRL_STOP
[7375] 1673386678.270583  [INFO] :  irrv-receiver: all stopped
[7375] 1673386678.270619  [INFO] :  ics-p2p-client: Deinit: Deleting server instance.
terminate called without an active exception
Aborted
```

Running via gdb provides this stack:
```
Thread 1 "ga-server-perio" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=135076149925696) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=135076149925696) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=135076149925696) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=135076149925696, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ad9de01f476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ad9de0057f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ad9de2c7bbe in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ad9de2d324c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ad9de2d32b7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ad9dcd58397 in vhal::client::CommandChannelInterface::~CommandChannelInterface() () from /opt/lib/libvhal-client.so.0
#9  0x00007ad9ddec438c in ga::webrtc::ICSP2PClient::~ICSP2PClient() () from /opt/lib/ga/server-webrtc.so
#10 0x00007ad9ddecd0b2 in std::shared_ptr<ga::webrtc::ICSP2PClient>::~shared_ptr() () from /opt/lib/ga/server-webrtc.so
#11 0x00007ad9de022495 in __run_exit_handlers (status=0, listp=0x7ad9de1f6838 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at ./stdlib/exit.c:113
#12 0x00007ad9de022610 in __GI_exit (status=<optimized out>) at ./stdlib/exit.c:143
#13 0x00007ad9de006d97 in __libc_start_call_main (main=main@entry=0x5a4b16ef1530 <main>, argc=argc@entry=14, argv=argv@entry=0x7ffc12898678) at ../sysdeps/nptl/libc_start_call_main.h:74
#14 0x00007ad9de006e40 in __libc_start_main_impl (main=0x5a4b16ef1530 <main>, argc=14, argv=0x7ffc12898678, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7ffc12898668) at ../csu/libc-start.c:392
#15 0x00005a4b16ef33f5 in _start ()
```

Issues happens in `vhal::client::CommandChannelInterface::~CommandChannelInterface()` since one of the working thread is not joined and program gets aborted as soon as not terminated thread runs out of scope. See (`ftc_talker_thread_` not joined):
https://github.com/projectceladon/libvhal-client/blob/3980f24a663396541313b27dc687ffd7454e44f1/source/command_channel_interface_impl.h#L306

**Comment by dvrogozh** [comment]
Fix in #8.
